name: icfpc2021
version: 0.1.0.0
synopsis: Pitiful attempt at solving ICFPC 2021
license: BSD3
author: "DNIWE :: a"
maintainer: ab@fmap.me

dependencies:
  - base >= 4.8
  - dniwechan

library:
  source-dirs: src

default-extensions:
  - ScopedTypeVariables
  - RecordWildCards
  - TypeFamilies
  - FlexibleContexts

ghc-options: -Wall

executables:
  main:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - icfpc2021
